=== oxillo/libims/VISTAS/doc/vistas_config.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- 
    * Copyright (c) 2018 Airbus Operations S.A.S                                  *
    *                                                                             *
    * This program and the accompanying materials are made available under the    *
    * terms of the Eclipse Public License v. 2.0 which is available at            *
    * http://www.eclipse.org/legal/epl-2.0, or the Eclipse Distribution License   *
    * v. 1.0 which is available at                                                *
    * http://www.eclipse.org/org/documents/edl-v10.php.                           *
    *                                                                             *
    * SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause                            *
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" attributeFormDefault="unqualified" version="1.0">

  <!-- Network node -->
  <xs:element name="Network">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ControlServers" type="servers-type" minOccurs="0" />
        <xs:element name="VirtualComponent" type="virtual-component-type" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:anyAttribute namespace="##other" processContents="skip" />
    </xs:complexType>
  </xs:element>


  <!-- Servers -->
  <xs:complexType name="servers-type">
    <xs:all>
      <xs:element name="PowerSupply" type="server-type" minOccurs="0" />
      <xs:element name="SignalOverriding" type="server-type" minOccurs="0" />
      <xs:element name="Synchronization" type="server-type" minOccurs="0" />
      <xs:element name="Modes" type="server-type" minOccurs="0" />
    </xs:all>
    <xs:anyAttribute namespace="##other" processContents="skip" />
  </xs:complexType>


  <!-- Server -->
  <xs:complexType name="server-type">
    <xs:attribute name="IPAddress" type="ip-type" use="required" />
    <xs:attribute name="Port" type="xs:positiveInteger" use="required" />
    <xs:anyAttribute namespace="##other" processContents="skip" />
  </xs:complexType>


  <!-- VirtualComponent node -->
  <xs:complexType name="virtual-component-type">
    <xs:choice minOccurs="1" maxOccurs="unbounded">
      <xs:element name="A429_Channel" type="base-channel-type" />
      <xs:element name="A664_Channel" type="base-channel-type" />
      <xs:element name="A825_Channel" type="base-channel-type" />
      <xs:element name="MIL_BUS_Channel" type="base-channel-type" />
      <xs:element name="Discrete_Channel" type="extended-channel-type" />
      <xs:element name="Analog_Channel" type="extended-channel-type" />
      <xs:element name="NAD_Channel" type="extended-channel-type" />
    </xs:choice>
    <xs:attribute name="Name" type="non-empty-type" use="required" />
    <xs:anyAttribute namespace="##other" processContents="skip" />
  </xs:complexType>


  <xs:complexType name="base-channel-type">
    <xs:sequence>
      <xs:element name="Socket" type="socket-type" maxOccurs="unbounded" />
      <xs:element name="Header" type="header-type" />
    </xs:sequence>
    <xs:attribute name="Name" type="non-empty-type" use="required" />
    <xs:attribute name="Direction" type="direction-type" use="required" />
    <xs:attribute name="MessageMaxSize" type="xs:positiveInteger" use="required" />
    <xs:attribute name="FifoSize" type="xs:positiveInteger" use="required" />
    <xs:attribute name="Comment" type="xs:string" use="optional" />
    <xs:attribute name="Speed" type="speed-type" use="optional" />
    <xs:attribute name="ICD" type="xs:string" use="optional" />
    <xs:anyAttribute namespace="##other" processContents="skip" />
  </xs:complexType>

  <xs:complexType name="extended-channel-type">
    <xs:complexContent>
      <xs:extension base="base-channel-type">
        <xs:sequence>
          <xs:element name="Signals" type="signals-type" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="socket-type">
    <xs:attribute name="DstIP" type="ip-type" use="required" />
    <xs:attribute name="DstPort" type="xs:positiveInteger" use="required" />
    <xs:attribute name="SrcIP" type="ip-type" use="optional" />
    <xs:attribute name="SrcPort" type="xs:positiveInteger" use="optional" />
    <xs:attribute name="MulticastInterfaceIP" type="ip-type" use="optional" />
    <xs:attribute name="TTL" type="xs:positiveInteger" use="optional" />
    <xs:anyAttribute namespace="##other" processContents="skip" />
  </xs:complexType>

  <xs:complexType name="header-type">
    <xs:attribute name="Src_Id" type="yes-no-type" use="optional" />
    <xs:attribute name="SN" type="yes-no-type" use="optional" />
    <xs:attribute name="QoS_Timestamp" type="yes-no-type" use="optional" />
    <xs:attribute name="Data_Timestamp" type="yes-no-type" use="optional" />
    <xs:anyAttribute namespace="##other" processContents="skip" />
  </xs:complexType>

  <xs:complexType name="signals-type">
    <xs:sequence>
      <xs:element name="Signal" type="signal-type" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:anyAttribute namespace="##other" processContents="skip" />
  </xs:complexType>


  <xs:complexType name="signal-type">
    <xs:attribute name="Name" type="non-empty-type" use="required" />
    <xs:attribute name="ByteOffset" type="xs:nonNegativeInteger" use="required" />
    <xs:attribute name="Type" type="xs:string" use="optional" />
    <xs:attribute name="Size" type="xs:positiveInteger" use="optional" />
    <xs:attribute name="Unit" type="xs:string" use="optional" />
    <xs:anyAttribute namespace="##other" processContents="skip" />
  </xs:complexType>



  <!-- Direction type -->
  <xs:simpleType name='direction-type'>
    <xs:restriction base="xs:string">
      <xs:enumeration value="In" />
      <xs:enumeration value="Out" />
    </xs:restriction>
  </xs:simpleType>


  <!-- Yes No type -->
  <xs:simpleType name='yes-no-type'>
    <xs:restriction base="xs:string">
      <xs:enumeration value="Yes" />
      <xs:enumeration value="No" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name='speed-type'>
    <xs:restriction base="xs:string">
      <xs:enumeration value="Low" />
      <xs:enumeration value="High" />
    </xs:restriction>
  </xs:simpleType>



  <!-- * * Standard simple types * -->
  <xs:simpleType name='non-empty-type'>
    <xs:restriction base='xs:token'>
      <xs:minLength value='1' />
    </xs:restriction>
  </xs:simpleType>


  <!-- * * IP type * -->
  <xs:simpleType name="ip-type">
    <xs:restriction base="xs:string">
      <xs:pattern value="([0-9]{1,3}\.){3}[0-9]{1,3}" />
    </xs:restriction>
  </xs:simpleType>


</xs:schema>

=== oxillo/libims/VISTAS/tests/tests/FT_INIT_VALUES/config/actor2/vistas.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!-- 
    * Copyright (c) 2018 Airbus Operations S.A.S                                  *
    *                                                                             *
    * This program and the accompanying materials are made available under the    *
    * terms of the Eclipse Public License v. 2.0 which is available at            *
    * http://www.eclipse.org/legal/epl-2.0, or the Eclipse Distribution License   *
    * v. 1.0 which is available at                                                *
    * http://www.eclipse.org/org/documents/edl-v10.php.                           *
    *                                                                             *
    * SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause                            *
-->

<Network xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vistas_config.xsd">
  <VirtualComponent Name="testVirtualComponent">
    <A664_Channel Name="firstEquipment_firstApplication_AFDX_IN_oneAFDX" Direction="In" MessageMaxSize="42" FifoSize="1">
      <Socket DstIP="226.23.12.4" DstPort="5078" />
      <Header Src_Id="No" SN="No" QoS_Timestamp="No" Data_Timestamp="No" />
    </A664_Channel>
    <A664_Channel Name="firstEquipment_firstApplication_AFDX_IN_smallAFDX" Direction="In" MessageMaxSize="10" FifoSize="1">
      <Socket DstIP="226.23.12.4" DstPort="5079" />
      <Header Src_Id="No" SN="No" QoS_Timestamp="No" Data_Timestamp="No" />
    </A664_Channel>
    <A429_Channel Name="firstEquipment_firstApplication_A429_IN_bus1" Direction="In" MessageMaxSize="8" FifoSize="1">
      <Socket DstIP="226.23.12.4" DstPort="5080" />
      <Header Src_Id="No" SN="No" QoS_Timestamp="No" Data_Timestamp="No" />
    </A429_Channel>
    <A825_Channel Name="firstEquipment_firstApplication_CAN_IN_bus1" Direction="In" MessageMaxSize="28" FifoSize="1">
      <Socket DstIP="226.23.12.4" DstPort="5081" />
      <Header Src_Id="No" SN="No" QoS_Timestamp="No" Data_Timestamp="No" />
    </A825_Channel>
  </VirtualComponent>
</Network>

=== oxillo/libims/VISTAS/tests/tests/FT_READ_AFDX_SAMPLING/config/actor1/vistas.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!-- 
    * Copyright (c) 2018 Airbus Operations S.A.S                                  *
    *                                                                             *
    * This program and the accompanying materials are made available under the    *
    * terms of the Eclipse Public License v. 2.0 which is available at            *
    * http://www.eclipse.org/legal/epl-2.0, or the Eclipse Distribution License   *
    * v. 1.0 which is available at                                                *
    * http://www.eclipse.org/org/documents/edl-v10.php.                           *
    *                                                                             *
    * SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause                            *
-->

<Network xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vistas_config.xsd">
  <VirtualComponent Name="testVirtualComponent">
    <A664_Channel Name="firstEquipment_firstApplication_AFDX_OUT_oneAFDX" Direction="Out" MessageMaxSize="42" FifoSize="1">
      <Socket DstIP="226.23.12.4" DstPort="5078" />
      <Header Src_Id="No" SN="No" QoS_Timestamp="No" Data_Timestamp="No" />
    </A664_Channel>
    <A664_Channel Name="firstEquipment_firstApplication_AFDX_OUT_OtherAFDX" Direction="Out" MessageMaxSize="21" FifoSize="1">
      <Socket DstIP="226.23.12.3" DstPort="5078" />
      <Header Src_Id="No" SN="No" QoS_Timestamp="No" Data_Timestamp="No" />
    </A664_Channel>
    <A664_Channel Name="firstEquipment_firstApplication_AFDX_OUT_bigAFDX" Direction="Out" MessageMaxSize="7600" FifoSize="1">
      <Socket DstIP="226.23.12.2" DstPort="5079" />
      <Header Src_Id="No" SN="No" QoS_Timestamp="No" Data_Timestamp="No" />
    </A664_Channel>
  </VirtualComponent>
</Network>

=== oxillo/libims/VISTAS/tests/tests/FT_INVALIDATE_MESSAGE/config/actor1/vistas.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!-- 
    * Copyright (c) 2018 Airbus Operations S.A.S                                  *
    *                                                                             *
    * This program and the accompanying materials are made available under the    *
    * terms of the Eclipse Public License v. 2.0 which is available at            *
    * http://www.eclipse.org/legal/epl-2.0, or the Eclipse Distribution License   *
    * v. 1.0 which is available at                                                *
    * http://www.eclipse.org/org/documents/edl-v10.php.                           *
    *                                                                             *
    * SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause                            *
-->

<Network xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vistas_config.xsd">
  <VirtualComponent Name="testVirtualComponent">
    <A664_Channel Name="firstEquipment_firstApplication_AFDX_OUT_AFDX_S_1" Direction="Out" MessageMaxSize="42" FifoSize="1">
      <Socket DstIP="226.23.12.1" DstPort="5078" />
      <Header Src_Id="No" SN="No" QoS_Timestamp="No" Data_Timestamp="No" />
    </A664_Channel>
    <A664_Channel Name="firstEquipment_firstApplication_AFDX_OUT_AFDX_S_2" Direction="Out" MessageMaxSize="21" FifoSize="1">
      <Socket DstIP="226.23.12.1" DstPort="5077" />
      <Header Src_Id="No" SN="No" QoS_Timestamp="No" Data_Timestamp="No" />
    </A664_Channel>
    <A664_Channel Name="firstEquipment_firstApplication_AFDX_OUT_AFDX_Q_1" Direction="Out" MessageMaxSize="42" FifoSize="2">
      <Socket DstIP="226.23.12.1" DstPort="5080" />
      <Header Src_Id="No" SN="No" QoS_Timestamp="No" Data_Timestamp="No" />
    </A664_Channel>
    <A664_Channel Name="firstEquipment_firstApplication_AFDX_OUT_AFDX_Q_2" Direction="Out" MessageMaxSize="21" FifoSize="4">
      <Socket DstIP="226.23.12.1" DstPort="5081" />
      <Header Src_Id="No" SN="No" QoS_Timestamp="No" Data_Timestamp="No" />
    </A664_Channel>
    <A429_Channel Name="firstEquipment_firstApplication_A429_OUT_A429_BUS1" Direction="Out" MessageMaxSize="20" FifoSize="1">
      <Socket DstIP="226.23.12.2" DstPort="5078" />
      <Header Src_Id="No" SN="No" QoS_Timestamp="No" Data_Timestamp="No" />
    </A429_Channel>
    <A429_Channel Name="firstEquipment_firstApplication_A429_OUT_A429_BUS2" Direction="Out" MessageMaxSize="24" FifoSize="1">
      <Socket DstIP="226.23.12.2" DstPort="5079" />
      <Header Src_Id="No" SN="No" QoS_Timestamp="No" Data_Timestamp="No" />
    </A429_Channel>
    <A825_Channel Name="firstEquipment_firstApplication_CAN_OUT_CAN_BUS1" Direction="Out" MessageMaxSize="28" FifoSize="1">
      <Socket DstIP="226.23.12.3" DstPort="5078" />
      <Header Src_Id="No" SN="No" QoS_Timestamp="No" Data_Timestamp="No" />
    </A825_Channel>
    <A825_Channel Name="firstEquipment_firstApplication_CAN_OUT_CAN_BUS2" Direction="Out" MessageMaxSize="28" FifoSize="1">
      <Socket DstIP="226.23.12.3" DstPort="5079" />
      <Header Src_Id="No" SN="No" QoS_Timestamp="No" Data_Timestamp="No" />
    </A825_Channel>
    <Discrete_Channel Name="firstEquipment_firstApplication_DISCRETE_OUT_port46453164" Direction="Out" MessageMaxSize="2" FifoSize="1">
      <Socket DstIP="226.23.12.4" DstPort="5078" />
      <Header Src_Id="No" SN="No" QoS_Timestamp="No" Data_Timestamp="No" />
      <Signals>
        <Signal Name="DISC1" ByteOffset="0" />
        <Signal Name="DISC2" ByteOffset="1" />
      </Signals>
    </Discrete_Channel>
    <Discrete_Channel Name="firstEquipment_firstApplication_DISCRETE_OUT_port2131597042" Direction="Out" MessageMaxSize="2" FifoSize="1">
      <Socket DstIP="226.23.12.4" DstPort="5079" />
      <Header Src_Id="No" SN="No" QoS_Timestamp="No" Data_Timestamp="No" />
      <Signals>
        <Signal Name="DISC3" ByteOffset="0" />
        <Signal Name="DISC4" ByteOffset="1" />
      </Signals>
    </Discrete_Channel>
    <Analog_Channel Name="firstEquipment_firstApplication_ANALOGUE_OUT_port1415289182" Direction="Out" MessageMaxSize="16" FifoSize="1">
      <Socket DstIP="226.23.12.5" DstPort="5078" />
      <Header Src_Id="No" SN="No" QoS_Timestamp="No" Data_Timestamp="No" />
      <Signals>
        <Signal Name="ANA1" ByteOffset="0" />
        <Signal Name="ANA2" ByteOffset="8" />
      </Signals>
    </Analog_Channel>
    <Analog_Channel Name="firstEquipment_firstApplication_ANALOGUE_OUT_port1990385139" Direction="Out" MessageMaxSize="16" FifoSize="1">
      <Socket DstIP="226.23.12.5" DstPort="5079" />
      <Header Src_Id="No" SN="No" QoS_Timestamp="No" Data_Timestamp="No" />
      <Signals>
        <Signal Name="ANA3" ByteOffset="0" />
        <Signal Name="ANA4" ByteOffset="8" />
      </Signals>
    </Analog_Channel>
    <NAD_Channel Name="firstEquipment_firstApplication_NAD_OUT_group1" Direction="Out" MessageMaxSize="10" FifoSize="1">
      <Socket DstIP="226.23.14.9" DstPort="5078" />
      <Header Src_Id="No" SN="No" QoS_Timestamp="No" Data_Timestamp="No" />
      <Signals>
        <Signal Name="grp1_nad1" ByteOffset="0" Size="4" />
        <Signal Name="grp1_nad2" ByteOffset="6" Size="1" />
      </Signals>
    </NAD_Channel>
    <NAD_Channel Name="firstEquipment_firstApplication_NAD_OUT_group2" Direction="Out" MessageMaxSize="18" FifoSize="1">
      <Socket DstIP="226.23.14.9" DstPort="5079" />
      <Header Src_Id="No" SN="No" QoS_Timestamp="No" Data_Timestamp="No" />
      <Signals>
        <Signal Name="grp2_nad1" ByteOffset="0" Size="8" />
        <Signal Name="grp2_nad2" ByteOffset="8" Size="10" />
      </Signals>
    </NAD_Channel>
  </VirtualComponent>
</Network>

=== oxillo/libims/VISTAS/tests/tests/FT_MULTI_VC/config/actor1/vistas0.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!-- 
    * Copyright (c) 2018 Airbus Operations S.A.S                                  *
    *                                                                             *
    * This program and the accompanying materials are made available under the    *
    * terms of the Eclipse Public License v. 2.0 which is available at            *
    * http://www.eclipse.org/legal/epl-2.0, or the Eclipse Distribution License   *
    * v. 1.0 which is available at                                                *
    * http://www.eclipse.org/org/documents/edl-v10.php.                           *
    *                                                                             *
    * SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause                            *
-->

<Network xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vistas_config.xsd">
    <VirtualComponent Name="GoodVirtualComponent">
        <A664_Channel Name="AFDX_S_O" Direction="Out" MessageMaxSize="42" FifoSize="1">
            <Socket DstIP="226.23.12.1" DstPort="7078" />
            <Header Src_Id="No" SN="No" QoS_Timestamp="No" Data_Timestamp="No" />
        </A664_Channel>
        <A664_Channel Name="AFDX_Q_O" Direction="Out" MessageMaxSize="42" FifoSize="2">
            <Socket DstIP="226.23.12.1" DstPort="7079" />
            <Header Src_Id="No" SN="No" QoS_Timestamp="No" Data_Timestamp="No" />
        </A664_Channel>
		<A664_Channel Name="AFDX_Q_I" Direction="In" MessageMaxSize="42" FifoSize="2">
            <Socket DstIP="226.23.12.1" DstPort="7080" />
            <Header Src_Id="No" SN="No" QoS_Timestamp="No" Data_Timestamp="No" />
        </A664_Channel>
		<A664_Channel Name="AFDX_S_I" Direction="In" MessageMaxSize="42" FifoSize="2">
            <Socket DstIP="226.23.12.1" DstPort="7081" />
            <Header Src_Id="No" SN="No" QoS_Timestamp="No" Data_Timestamp="No" />
        </A664_Channel>
    </VirtualComponent>
</Network>

=== oxillo/libims/VISTAS/tests/tests/FT_READ_AFDX_SAMPLING/config/actor2/vistas.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!-- 
    * Copyright (c) 2018 Airbus Operations S.A.S                                  *
    *                                                                             *
    * This program and the accompanying materials are made available under the    *
    * terms of the Eclipse Public License v. 2.0 which is available at            *
    * http://www.eclipse.org/legal/epl-2.0, or the Eclipse Distribution License   *
    * v. 1.0 which is available at                                                *
    * http://www.eclipse.org/org/documents/edl-v10.php.                           *
    *                                                                             *
    * SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause                            *
-->

<Network xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vistas_config.xsd">
  <VirtualComponent Name="testVirtualComponent">
    <A664_Channel Name="firstEquipment_firstApplication_AFDX_IN_oneAFDX" Direction="In" MessageMaxSize="42" FifoSize="1">
      <Socket DstIP="226.23.12.4" DstPort="5078" />
      <Header Src_Id="No" SN="No" QoS_Timestamp="No" Data_Timestamp="No" />
    </A664_Channel>
    <A664_Channel Name="firstEquipment_firstApplication_AFDX_IN_OtherAFDX" Direction="In" MessageMaxSize="21" FifoSize="1">
      <Socket DstIP="226.23.12.3" DstPort="5078" />
      <Header Src_Id="No" SN="No" QoS_Timestamp="No" Data_Timestamp="No" />
    </A664_Channel>
    <A664_Channel Name="firstEquipment_firstApplication_AFDX_IN_bigAFDX" Direction="In" MessageMaxSize="7600" FifoSize="1">
      <Socket DstIP="226.23.12.2" DstPort="5079" />
      <Header Src_Id="No" SN="No" QoS_Timestamp="No" Data_Timestamp="No" />
    </A664_Channel>
    <A664_Channel Name="firstEquipment_firstApplication_AFDX_IN_queuing_message" Direction="In" MessageMaxSize="21" FifoSize="4">
      <Socket DstIP="226.23.22.2" DstPort="6077" />
      <Header Src_Id="No" SN="No" QoS_Timestamp="No" Data_Timestamp="No" />
    </A664_Channel>
    <A664_Channel Name="firstEquipment_firstApplication_AFDX_OUT_output_message" Direction="Out" MessageMaxSize="42" FifoSize="1">
      <Socket DstIP="226.23.22.20" DstPort="6077" />
      <Header Src_Id="No" SN="No" QoS_Timestamp="No" Data_Timestamp="No" />
    </A664_Channel>
  </VirtualComponent>
</Network>

=== oxillo/libims/VISTAS/tests/tests/FT_POP_AFDX_QUEUING/config/actor1/vistas.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!-- 
    * Copyright (c) 2018 Airbus Operations S.A.S                                  *
    *                                                                             *
    * This program and the accompanying materials are made available under the    *
    * terms of the Eclipse Public License v. 2.0 which is available at            *
    * http://www.eclipse.org/legal/epl-2.0, or the Eclipse Distribution License   *
    * v. 1.0 which is available at                                                *
    * http://www.eclipse.org/org/documents/edl-v10.php.                           *
    *                                                                             *
    * SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause                            *
-->

<Network xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vistas_config.xsd">
  <VirtualComponent Name="testVirtualComponent">
    <A664_Channel Name="firstEquipment_firstApplication_AFDX_OUT_AFDXQ1" Direction="Out" MessageMaxSize="42" FifoSize="3">
      <Socket DstIP="226.23.12.4" DstPort="5078" />
      <Header Src_Id="No" SN="No" QoS_Timestamp="No" Data_Timestamp="No" />
    </A664_Channel>
    <A664_Channel Name="firstEquipment_firstApplication_AFDX_OUT_AFDXQ2" Direction="Out" MessageMaxSize="21" FifoSize="4">
      <Socket DstIP="226.23.12.4" DstPort="5077" />
      <Header Src_Id="No" SN="No" QoS_Timestamp="No" Data_Timestamp="No" />
    </A664_Channel>
  </VirtualComponent>
</Network>
