=== oxillo/libims/doc/ims_config.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!-- 
    * Copyright (c) 2018 Airbus Operations S.A.S                                  *
    *                                                                             *
    * This program and the accompanying materials are made available under the    *
    * terms of the Eclipse Public License v. 2.0 which is available at            *
    * http://www.eclipse.org/legal/epl-2.0, or the Eclipse Distribution License   *
    * v. 1.0 which is available at                                                *
    * http://www.eclipse.org/org/documents/edl-v10.php.                           *
    *                                                                             *
    * SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause                            *
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
           elementFormDefault="unqualified" 
           attributeFormDefault="unqualified" 
           version="1.0">

  <!--
      * 
      * VirtualComponent node
      *
  -->
  <xs:element name="VirtualComponent">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="DataExchange" type="data-exchange-type" minOccurs="0" maxOccurs="1"/>
        <xs:element name="Equipment"    type="equipment-type"     minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="Name"                type="non-empty-type"        use="required" />
      <xs:attribute name="ProdId"              type="xs:nonNegativeInteger" use="optional" />
      <xs:attribute name="StartupRunningState" type="running-state-type"    use="optional" />
      <xs:attribute name="PowerState"          type="power-state-type"      use="optional" />
      <xs:anyAttribute namespace="##other" processContents="skip"/>
    </xs:complexType>
  </xs:element>


  <!--
      *
      * Equipment node
      *
  -->
  <xs:complexType name="equipment-type">
    <xs:sequence>
      <xs:element name="DataExchange" type="data-exchange-type" minOccurs="0" maxOccurs="1"/>
      <xs:element name="Application"  type="application-type"   minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="Name" type="non-empty-type" use="required" />
    <xs:anyAttribute namespace="##other" processContents="skip"/>
  </xs:complexType>


  <!--
      *
      * Application node
      *
  -->
  <xs:complexType name="application-type">
    <xs:sequence>
      <xs:element name="DataExchange" type="data-exchange-type" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
    <xs:attribute name="Name" type="non-empty-type" use="required" />
    <xs:anyAttribute namespace="##other" processContents="skip"/>
  </xs:complexType>



  <!--
      *
      * DataExchange node
      *
  -->
  <xs:complexType name="data-exchange-type">
    <xs:all>
      <xs:element name="AFDX"     type="afdx-type"     minOccurs="0" maxOccurs="1"/>
      <xs:element name="A429"     type="a429-type"     minOccurs="0" maxOccurs="1"/>
      <xs:element name="CAN"      type="can-type"      minOccurs="0" maxOccurs="1"/>
      <xs:element name="DISCRETE" type="discrete-type" minOccurs="0" maxOccurs="1"/>
      <xs:element name="ANALOGUE" type="analogue-type" minOccurs="0" maxOccurs="1"/>
      <xs:element name="NAD"      type="nad-type"      minOccurs="0" maxOccurs="1"/>
    </xs:all>
    <xs:anyAttribute namespace="##other" processContents="skip"/>
  </xs:complexType>



  <!--
      *
      * AFDX node
      *
  -->
  <xs:complexType name="afdx-type">
    <xs:all>
      <xs:element name="ConsumedData" type="afdx-direction-type" minOccurs="0" maxOccurs="1"/>
      <xs:element name="ProducedData" type="afdx-direction-type" minOccurs="0" maxOccurs="1"/>
    </xs:all>
    <xs:anyAttribute namespace="##other" processContents="skip"/>
  </xs:complexType>

  <xs:complexType name="afdx-direction-type">
    <xs:choice maxOccurs="unbounded">
      <xs:element name="SamplingMessage" type="afdx-sampling-type" minOccurs="0" maxOccurs="1"/>
      <xs:element name="QueuingMessage"  type="afdx-queuing-type"  minOccurs="0" maxOccurs="1"/>      
    </xs:choice>
    <xs:anyAttribute namespace="##other" processContents="skip"/>
  </xs:complexType>

  <xs:complexType name="afdx-sampling-type">
    <xs:attribute name="Name"               type="non-empty-type"        use="required" />
    <xs:attribute name="LocalName"          type="non-empty-type"        use="required" />
    <xs:attribute name="MessageSizeBytes"   type="xs:positiveInteger"    use="required" />
    <xs:attribute name="ValidityDurationUs" type="xs:nonNegativeInteger" use="required" />
    <xs:attribute name="PeriodUs"           type="xs:nonNegativeInteger" use="optional" />
    <xs:anyAttribute namespace="##other" processContents="skip"/>
  </xs:complexType>

  <xs:complexType name="afdx-queuing-type">
    <xs:attribute name="Name"         type="non-empty-type"     use="required" />
    <xs:attribute name="LocalName"    type="non-empty-type"     use="required" />
    <xs:attribute name="MaxSizeBytes" type="xs:positiveInteger" use="required" />
    <xs:attribute name="QueueDepth"   type="xs:positiveInteger" use="required" />
    <xs:anyAttribute namespace="##other" processContents="skip"/>
  </xs:complexType>



  <!--
      *
      * A429 node
      *
  -->
  <xs:complexType name="a429-type">
    <xs:all>
      <xs:element name="ConsumedData" type="a429-direction-type" minOccurs="0" maxOccurs="1"/>
      <xs:element name="ProducedData" type="a429-direction-type" minOccurs="0" maxOccurs="1"/>
    </xs:all>
    <xs:anyAttribute namespace="##other" processContents="skip"/>
  </xs:complexType>

  <xs:complexType name="a429-direction-type">
    <xs:sequence>
      <xs:element name="Bus" type="a429-bus-type" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:anyAttribute namespace="##other" processContents="skip"/>
  </xs:complexType>

  <xs:complexType name="a429-bus-type">
    <xs:choice maxOccurs="unbounded">
      <xs:element name="SamplingLabel" type="a429-sampling-type" minOccurs="0" maxOccurs="1"/>
      <xs:element name="QueuingLabel"  type="a429-queuing-type"  minOccurs="0" maxOccurs="1"/>      
    </xs:choice>
    <xs:attribute name="Name" type="non-empty-type" use="required" />
    <xs:anyAttribute namespace="##other" processContents="skip"/>
  </xs:complexType>

  <xs:complexType name="a429-sampling-type">
    <xs:attribute name="Number"             type="label-number-type"       use="required" />
    <xs:attribute name="Sdi"                type="sdi-type"                use="required" />
    <xs:attribute name="LocalName"          type="non-empty-type"          use="required" />
    <xs:attribute name="ValidityDurationUs" type="xs:nonNegativeInteger"   use="required" />
    <xs:attribute name="PeriodUs"           type="xs:nonNegativeInteger"   use="optional" />
    <xs:anyAttribute namespace="##other" processContents="skip"/>
  </xs:complexType>

  <xs:complexType name="a429-queuing-type">
    <xs:attribute name="Number"             type="label-number-type"       use="required" />
    <xs:attribute name="Sdi"                type="sdi-type"                use="required" />
    <xs:attribute name="LocalName"          type="non-empty-type"          use="required" />
    <xs:attribute name="QueueDepth"         type="xs:nonNegativeInteger"   use="required" />
    <xs:anyAttribute namespace="##other" processContents="skip"/>
  </xs:complexType>



  <!--
      *
      * CAN node
      *
  -->
  <xs:complexType name="can-type">
    <xs:all>
      <xs:element name="ConsumedData" type="can-direction-type" minOccurs="0" maxOccurs="1"/>
      <xs:element name="ProducedData" type="can-direction-type" minOccurs="0" maxOccurs="1"/>
    </xs:all>
    <xs:anyAttribute namespace="##other" processContents="skip"/>
  </xs:complexType>

  <xs:complexType name="can-direction-type">
    <xs:sequence>
      <xs:element name="Bus" type="can-bus-type" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:anyAttribute namespace="##other" processContents="skip"/>
  </xs:complexType>

  <xs:complexType name="can-bus-type">
    <xs:choice maxOccurs="unbounded">
      <xs:element name="SamplingMessage" type="can-sampling-type" minOccurs="0" maxOccurs="1">
        <xs:key name="att">
            <xs:selector xpath="."/>
            <xs:field xpath="@DefaultId|@Id"/>
        </xs:key>
      </xs:element>
      <xs:element name="QueuingMessage"  type="can-queuing-type"  minOccurs="0" maxOccurs="1"/>      
    </xs:choice>
    <xs:attribute name="Name" type="non-empty-type" use="required" />
    <xs:anyAttribute namespace="##other" processContents="skip"/>
  </xs:complexType>

  <xs:complexType name="can-sampling-type">
    <xs:simpleContent>
        <xs:extension base="xs:string">
            <xs:attribute name="DefaultId"          type="can-id-type"                            />
            <xs:attribute name="Id"                 type="can-id-type"                            />
            <xs:attribute name="LocalName"          type="non-empty-type"          use="required" />
            <xs:attribute name="MessageSizeBytes"   type="xs:nonNegativeInteger"   use="required" />
            <xs:attribute name="ValidityDurationUs" type="xs:nonNegativeInteger"   use="required" />
            <xs:attribute name="PeriodUs"           type="xs:nonNegativeInteger"   use="optional" />
            <xs:anyAttribute namespace="##other" processContents="skip"/>
        </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="can-queuing-type">
    <xs:anyAttribute processContents="skip"/> <!-- Not supported yet -->
  </xs:complexType>

  <!--
      *
      * DISCRETE node
      *
  -->
  <xs:complexType name="discrete-type">
    <xs:all>
      <xs:element name="ConsumedData" type="discrete-direction-type" minOccurs="0" maxOccurs="1"/>
      <xs:element name="ProducedData" type="discrete-direction-type" minOccurs="0" maxOccurs="1"/>
    </xs:all>
    <xs:anyAttribute namespace="##other" processContents="skip"/>
  </xs:complexType>

  <xs:complexType name="discrete-direction-type">
    <xs:sequence>
      <xs:element name="Signal" type="discrete-signal-type" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:anyAttribute namespace="##other" processContents="skip"/>
  </xs:complexType>

  <xs:complexType name="discrete-signal-type">
    <xs:attribute name="Name"          type="non-empty-type"        use="required" />
    <xs:attribute name="LocalName"     type="non-empty-type"        use="required" />
    <xs:attribute name="TrueState"     type="xs:nonNegativeInteger" use="optional" />
    <xs:attribute name="FalseState"    type="xs:nonNegativeInteger" use="optional" />
    <xs:attribute name="HWPP"          type="hwpp-value-type"       use="optional" />
    <xs:attribute name="PeriodUs"      type="xs:nonNegativeInteger" use="optional" />
    <xs:attribute name="ValidityDurationUs" type="xs:nonNegativeInteger" use="optional" />
    <xs:anyAttribute namespace="##other" processContents="skip"/>
  </xs:complexType>



  <!--
      *
      * ANALOGUE node
      *
  -->
  <xs:complexType name="analogue-type">
    <xs:all>
      <xs:element name="ConsumedData" type="analogue-direction-type" minOccurs="0" maxOccurs="1"/>
      <xs:element name="ProducedData" type="analogue-direction-type" minOccurs="0" maxOccurs="1"/>
    </xs:all>
    <xs:anyAttribute namespace="##other" processContents="skip"/>
  </xs:complexType>

  <xs:complexType name="analogue-direction-type">
    <xs:sequence>
      <xs:element name="Signal" type="analogue-signal-type" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:anyAttribute namespace="##other" processContents="skip"/>
  </xs:complexType>

  <xs:complexType name="analogue-signal-type">
    <xs:attribute name="Name"          type="non-empty-type" use="required" />
    <xs:attribute name="LocalName"     type="non-empty-type" use="required" />
    <xs:attribute name="ScaleFactor"   type="xs:float"       use="required" />
    <xs:attribute name="Offset"        type="xs:float"       use="required" />
    <xs:attribute name="PeriodUs"      type="xs:nonNegativeInteger" use="optional" />
    <xs:attribute name="ValidityDurationUs" type="xs:nonNegativeInteger" use="optional" />
    <xs:anyAttribute namespace="##other" processContents="skip"/>
  </xs:complexType>


  <!--
      *
      * NAD node
      *
  -->
  <xs:complexType name="nad-type">
    <xs:all>
      <xs:element name="ConsumedData" type="nad-direction-type" minOccurs="0" maxOccurs="1"/>
      <xs:element name="ProducedData" type="nad-direction-type" minOccurs="0" maxOccurs="1"/>
    </xs:all>
    <xs:anyAttribute namespace="##other" processContents="skip"/>
  </xs:complexType>

  <xs:complexType name="nad-direction-type">
    <xs:sequence>
      <xs:element name="Message" type="nad-message-type" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
    <xs:anyAttribute namespace="##other" processContents="skip"/>
  </xs:complexType>

  <xs:complexType name="nad-message-type">
    <xs:attribute name="Name"             type="non-empty-type"     use="required" />
    <xs:attribute name="LocalName"        type="non-empty-type"     use="required" />
    <xs:attribute name="MessageSizeBytes" type="xs:positiveInteger" use="required" />
    <xs:attribute name="PeriodUs"         type="xs:nonNegativeInteger" use="optional" />
    <xs:attribute name="MessageType"       type="message-type-enum" use="optional" />
    <xs:attribute name="MessageDimension1" type="xs:nonNegativeInteger" use="optional" />
    <xs:attribute name="MessageDimension2" type="xs:nonNegativeInteger" use="optional" />
    <xs:anyAttribute namespace="##other" processContents="skip"/>
  </xs:complexType>



  <!--
      *
      * Standard simple types
      *
  -->
  <xs:simpleType name='non-empty-type'>
    <xs:restriction base='xs:token'>
      <xs:minLength value='1'/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name='label-number-type'>
    <xs:restriction base='xs:string'>
      <xs:pattern value='[0-3]?[0-7]?[0-7]'/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name='sdi-type'>
    <xs:restriction base='xs:string'>
      <xs:enumeration value="00"/>
      <xs:enumeration value="01"/>
      <xs:enumeration value="10"/>
      <xs:enumeration value="11"/>
      <xs:enumeration value="DD"/>
      <xs:enumeration value="XX"/>
      <xs:enumeration value="NU"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name='message-type-enum'>
    <xs:restriction base='xs:string'>
      <xs:enumeration value="BOOLEAN"/>
      <xs:enumeration value="C08"/>
      <xs:enumeration value="F32"/>
      <xs:enumeration value="F64"/>
      <xs:enumeration value="I16"/>
      <xs:enumeration value="I32"/>
      <xs:enumeration value="I64"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name='discrete-value-type'>
    <xs:restriction base='xs:string'>
      <xs:enumeration value="0"/>
      <xs:enumeration value="1"/>
      <xs:enumeration value="true"/>
      <xs:enumeration value="false"/>
      <xs:enumeration value="TRUE"/>
      <xs:enumeration value="FALSE"/>
    </xs:restriction>
  </xs:simpleType>


  <xs:simpleType name='hwpp-value-type'>
    <xs:restriction base='xs:string'>
      <xs:enumeration value="yes"/>
      <xs:enumeration value="no"/>
      <xs:enumeration value="YES"/>
      <xs:enumeration value="NO"/>
    </xs:restriction>
  </xs:simpleType>


  <xs:simpleType name='can-id-type'>
    <xs:restriction base="xs:string">
      <xs:pattern value='[0-9A-Fa-f]{1,8}'/>
    </xs:restriction>
  </xs:simpleType>
  

  <xs:simpleType name='running-state-type'>
    <xs:restriction base='xs:string'>
      <xs:enumeration value="run"/>
      <xs:enumeration value="step"/>
      <xs:enumeration value="hold"/>
      <xs:enumeration value="reset"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name='power-state-type'>
    <xs:restriction base='xs:string'>
      <xs:enumeration value="on"/>
      <xs:enumeration value="off"/>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== oxillo/libims/VISTAS/tests/tests/FT_ACCESSORS/config/actor1/ims.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!-- 
    * Copyright (c) 2018 Airbus Operations S.A.S                                  *
    *                                                                             *
    * This program and the accompanying materials are made available under the    *
    * terms of the Eclipse Public License v. 2.0 which is available at            *
    * http://www.eclipse.org/legal/epl-2.0, or the Eclipse Distribution License   *
    * v. 1.0 which is available at                                                *
    * http://www.eclipse.org/org/documents/edl-v10.php.                           *
    *                                                                             *
    * SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause                            *
-->

<VirtualComponent xmlns:ex="http://airbus.com/modelingandsimulation/vsim/extension" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Name="testVirtualComponent" xsi:noNamespaceSchemaLocation="ims_config.xsd">
  <DataExchange>
    <NAD>
      <ProducedData>
        <Message Name="grp1_nad1_O" LocalName="NAD_Message1_O" MessageSizeBytes="1" PeriodUs="50000" />
      </ProducedData>
      <ConsumedData>
        <Message Name="grp1_nad1_I" LocalName="NAD_Message1_I" MessageSizeBytes="5" />
      </ConsumedData>
    </NAD>
  </DataExchange>
  <Equipment Name="firstEquipment">
    <DataExchange>
      <NAD>
        <ConsumedData>
          <Message Name="grp1_nad1_I_1" LocalName="NAD_Message1_I" MessageSizeBytes="5" />
        </ConsumedData>
      </NAD>
    </DataExchange>
    <Application Name="firstApplication">
      <DataExchange>
        <A429>
          <ProducedData>
            <Bus Name="firstEquipment_firstApplication_A429_OUT_bus1">
              <SamplingLabel Sdi="01" LocalName="bus1_l1_O" Number="024" ValidityDurationUs="3750000000" />
              <QueuingLabel Sdi="11" LocalName="bus1_l2_O" Number="024" QueueDepth="4" />
            </Bus>
            <Bus Name="firstEquipment_firstApplication_A429_OUT_bus2">
              <SamplingLabel Sdi="01" LocalName="bus2_l1_O" Number="024" ValidityDurationUs="60000" />
              <QueuingLabel Sdi="01" LocalName="bus2_l2_O" Number="123" QueueDepth="5" />
            </Bus>
          </ProducedData>
          <ConsumedData>
            <Bus Name="firstEquipment_firstApplication_A429_IN_bus1">
              <SamplingLabel Sdi="01" LocalName="bus1_l1_I" Number="024" ValidityDurationUs="50000" />
              <QueuingLabel Sdi="11" LocalName="bus1_l2_I" Number="024" QueueDepth="4" />
            </Bus>
            <Bus Name="firstEquipment_firstApplication_A429_IN_bus2">
              <SamplingLabel Sdi="01" LocalName="bus2_l1_I" Number="024" ValidityDurationUs="60000" />
              <QueuingLabel Sdi="01" LocalName="bus2_l2_I" Number="123" QueueDepth="5" />
            </Bus>
          </ConsumedData>
        </A429>
        <AFDX>
          <ProducedData>
            <SamplingMessage Name="firstEquipment_firstApplication_AFDX_OUT_oneAFDX_O" LocalName="AFDXLocalName_O" MessageSizeBytes="42" ValidityDurationUs="50000" />
            <SamplingMessage Name="firstEquipment_firstApplication_AFDX_OUT_OtherAFDX_O" LocalName="OtherAFDXLocalName_O" MessageSizeBytes="21" ValidityDurationUs="50000" />
            <QueuingMessage Name="firstEquipment_firstApplication_AFDX_OUT_AFDXQ1_O" LocalName="AFDXLocalQ1_O" MaxSizeBytes="42" QueueDepth="2" />
            <QueuingMessage Name="firstEquipment_firstApplication_AFDX_OUT_AFDXQ2_O" LocalName="AFDXLocalQ2_O" MaxSizeBytes="21" QueueDepth="4" />
          </ProducedData>
          <ConsumedData>
            <QueuingMessage Name="firstEquipment_firstApplication_AFDX_IN_AFDXQ1_I" LocalName="AFDXLocalQ1_I" MaxSizeBytes="42" QueueDepth="2" />
            <QueuingMessage Name="firstEquipment_firstApplication_AFDX_IN_AFDXQ2_I" LocalName="AFDXLocalQ2_I" MaxSizeBytes="21" QueueDepth="4" />
            <SamplingMessage Name="firstEquipment_firstApplication_AFDX_IN_oneAFDX_I" LocalName="AFDXLocalName_I" MessageSizeBytes="42" ValidityDurationUs="50000" />
            <SamplingMessage Name="firstEquipment_firstApplication_AFDX_IN_OtherAFDX_I" LocalName="OtherAFDXLocalName_I" MessageSizeBytes="21" ValidityDurationUs="50000" />
          </ConsumedData>
        </AFDX>
        <ANALOGUE>
          <ProducedData>
            <Signal Name="grp1_sig1_O" LocalName="signal1_O" ScaleFactor="1.5" Offset="0" PeriodUs="50000" />
            <Signal Name="grp1_sig2_O" LocalName="signal2_O" ScaleFactor="2" Offset="3.5" PeriodUs="50000" />
            <Signal Name="grp2_sig1_O" LocalName="signal3_O" ScaleFactor="0.5" Offset="-4.2" PeriodUs="60000" />
            <Signal Name="grp2_sig2_O" LocalName="signal4_O" ScaleFactor="-1.5" Offset="200" PeriodUs="60000" />
          </ProducedData>
          <ConsumedData>
            <Signal Name="grp1_sig1_I" LocalName="signal1_I" ScaleFactor="1.5" Offset="0" />
            <Signal Name="grp1_sig2_I" LocalName="signal2_I" ScaleFactor="2" Offset="3.5" />
            <Signal Name="grp2_sig1_I" LocalName="signal3_I" ScaleFactor="0.5" Offset="-4.2" />
            <Signal Name="grp2_sig2_I" LocalName="signal4_I" ScaleFactor="-1.5" Offset="200" />
          </ConsumedData>
        </ANALOGUE>
        <CAN>
          <ProducedData>
            <Bus Name="firstEquipment_firstApplication_CAN_OUT_bus1_O">
              <SamplingMessage DefaultId="1F" LocalName="bus1_m1_O" MessageSizeBytes="4" ValidityDurationUs="50000" />
              <SamplingMessage DefaultId="20" LocalName="bus1_m2_O" MessageSizeBytes="8" ValidityDurationUs="60000" />
            </Bus>
            <Bus Name="firstEquipment_firstApplication_CAN_OUT_bus2_O">
              <SamplingMessage DefaultId="10" LocalName="bus2_m1_O" MessageSizeBytes="8" ValidityDurationUs="60000" />
              <SamplingMessage DefaultId="30" LocalName="bus2_m2_O" MessageSizeBytes="4" ValidityDurationUs="50000" />
            </Bus>
          </ProducedData>
          <ConsumedData>
            <Bus Name="firstEquipment_firstApplication_CAN_IN_bus1_I">
              <SamplingMessage DefaultId="1F" LocalName="bus1_m1_I" MessageSizeBytes="4" ValidityDurationUs="50000" />
              <SamplingMessage DefaultId="20" LocalName="bus1_m2_I" MessageSizeBytes="8" ValidityDurationUs="60000" />
            </Bus>
            <Bus Name="firstEquipment_firstApplication_CAN_IN_bus2_I">
              <SamplingMessage DefaultId="10" LocalName="bus2_m1_I" MessageSizeBytes="8" ValidityDurationUs="60000" />
              <SamplingMessage DefaultId="30" LocalName="bus2_m2_I" MessageSizeBytes="4" ValidityDurationUs="50000" />
            </Bus>
          </ConsumedData>
        </CAN>
        <DISCRETE>
          <ProducedData>
            <Signal Name="grp1_sig1_O" LocalName="DISC_signal1_O" TrueState="0" PeriodUs="50000" />
            <Signal Name="grp1_sig2_O" LocalName="DISC_signal2_O" FalseState="42" PeriodUs="50000" />
            <Signal Name="grp2_sig1_O" LocalName="DISC_signal3_O" PeriodUs="60000" />
            <Signal Name="grp2_sig2_O" LocalName="DISC_signal4_O" PeriodUs="60000" />
          </ProducedData>
          <ConsumedData>
            <Signal Name="grp1_sig1_I" LocalName="DISC_signal1_I" TrueState="2" FalseState="0" />
            <Signal Name="grp1_sig2_I" LocalName="DISC_signal2_I" />
            <Signal Name="grp2_sig1_I" LocalName="DISC_signal3_I" />
            <Signal Name="grp2_sig2_I" LocalName="DISC_signal4_I" />
          </ConsumedData>
        </DISCRETE>
        <NAD>
          <ProducedData>
            <Message Name="grp1_nad1_O_1" LocalName="NAD_Message1_O" MessageSizeBytes="4" PeriodUs="50000" MessageType="C08" />
            <Message Name="grp1_nad2_O" LocalName="NAD_Message2_O" MessageSizeBytes="1" PeriodUs="50000" MessageDimension1="1" />
            <Message Name="grp2_nad1_O" LocalName="NAD_Message3_O" MessageSizeBytes="8" PeriodUs="60000" MessageType="F64" />
            <Message Name="grp2_nad2_O" LocalName="NAD_Message4_O" MessageSizeBytes="10" PeriodUs="60000"   />
          </ProducedData>
          <ConsumedData>
            <Message Name="grp1_nad1_I_2" LocalName="NAD_Message1_I" MessageSizeBytes="4" />
            <Message Name="grp1_nad2_I" LocalName="NAD_Message2_I" MessageSizeBytes="1" />
            <Message Name="grp2_nad1_I" LocalName="NAD_Message3_I" MessageSizeBytes="8" />
            <Message Name="grp2_nad2_I" LocalName="NAD_Message4_I" MessageSizeBytes="10" MessageDimension1="2" MessageDimension2="5" />
          </ConsumedData>
        </NAD>
      </DataExchange>
    </Application>
    <Application Name="secondApplication">
      <DataExchange>
        <NAD>
          <ProducedData>
            <Message Name="grp1_nad1_O_2" LocalName="NAD_Message1_O" MessageSizeBytes="4" PeriodUs="50000" />
          </ProducedData>
        </NAD>
      </DataExchange>
    </Application>
  </Equipment>
  <Equipment Name="secondEquipment" />
</VirtualComponent>

=== oxillo/libims/VISTAS/tests/tests/FT_PUSH_A429_QUEUING/config/actor2/ims.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!-- 
    * Copyright (c) 2018 Airbus Operations S.A.S                                  *
    *                                                                             *
    * This program and the accompanying materials are made available under the    *
    * terms of the Eclipse Public License v. 2.0 which is available at            *
    * http://www.eclipse.org/legal/epl-2.0, or the Eclipse Distribution License   *
    * v. 1.0 which is available at                                                *
    * http://www.eclipse.org/org/documents/edl-v10.php.                           *
    *                                                                             *
    * SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause                            *
-->

<VirtualComponent xmlns:ex="http://airbus.com/modelingandsimulation/vsim/extension" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Name="testVirtualComponent" xsi:noNamespaceSchemaLocation="ims_config.xsd">
  <Equipment Name="firstEquipment">
    <Application Name="firstApplication">
      <DataExchange>
        <A429>
          <ConsumedData>
            <Bus Name="firstEquipment_firstApplication_A429_IN_bus1">
              <SamplingLabel Sdi="01" LocalName="bus1_l1" Number="024" ValidityDurationUs="50000" />
              <QueuingLabel Sdi="11" LocalName="bus1_l2" Number="024" QueueDepth="4" />
            </Bus>
            <Bus Name="firstEquipment_firstApplication_A429_IN_bus2">
              <SamplingLabel Sdi="01" LocalName="bus2_l1" Number="024" ValidityDurationUs="60000" />
              <QueuingLabel Sdi="01" LocalName="bus2_l2" Number="123" QueueDepth="5" />
            </Bus>
          </ConsumedData>
        </A429>
      </DataExchange>
    </Application>
  </Equipment>
</VirtualComponent>

=== oxillo/libims/VISTAS/tests/tests/FT_POP_AFDX_QUEUING/config/actor2/ims.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!-- 
    * Copyright (c) 2018 Airbus Operations S.A.S                                  *
    *                                                                             *
    * This program and the accompanying materials are made available under the    *
    * terms of the Eclipse Public License v. 2.0 which is available at            *
    * http://www.eclipse.org/legal/epl-2.0, or the Eclipse Distribution License   *
    * v. 1.0 which is available at                                                *
    * http://www.eclipse.org/org/documents/edl-v10.php.                           *
    *                                                                             *
    * SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause                            *
-->

<VirtualComponent xmlns:ex="http://airbus.com/modelingandsimulation/vsim/extension" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Name="testVirtualComponent" xsi:noNamespaceSchemaLocation="ims_config.xsd">
  <Equipment Name="firstEquipment">
    <Application Name="firstApplication">
      <DataExchange>
        <AFDX>
          <ConsumedData>
            <QueuingMessage Name="firstEquipment_firstApplication_AFDX_IN_AFDXQ1" LocalName="AFDXLocalQ1" MaxSizeBytes="42" QueueDepth="2" />
            <QueuingMessage Name="firstEquipment_firstApplication_AFDX_IN_AFDXQ2" LocalName="AFDXLocalQ2" MaxSizeBytes="21" QueueDepth="4" />
            <SamplingMessage Name="firstEquipment_firstApplication_AFDX_IN_AFDXsampling" LocalName="AFDXsampling" MessageSizeBytes="21" ValidityDurationUs="50000" />
          </ConsumedData>
          <ProducedData>
            <QueuingMessage Name="firstEquipment_firstApplication_AFDX_OUT_AFDXoutput" LocalName="AFDXoutput" MaxSizeBytes="42" QueueDepth="2" />
          </ProducedData>
        </AFDX>
      </DataExchange>
    </Application>
  </Equipment>
</VirtualComponent>
